### ISSUE TITLE
Improving the 'Fork me on github' tag

### ISSUE THREAD

**Issue by vsc-github** [spezzino/hfchecker#19]
The current tag isn't center-aligned and looks kinda congested. 
Can I fix it?

I tried it on my local and this it what it would look like.

[![Screen Shot 2016-10-24 at 1.41.10 PM.png](https://s9.postimg.org/t7yz4lo7j/Screen_Shot_2016_10_24_at_1_41_10_PM.png)](https://postimg.org/image/o9bgq2kej/)

Would love to contribute to your project.

**Comment by spezzino** [comment]
Hello @mastercod3r. Repository is open for contributions. Just submit a pull request with these changes and I will merge them.
