### ISSUE TITLE
Add share buttons

### ISSUE THREAD

**Issue by spezzino** [spezzino/hfchecker#3]
Add buttons to share on social media

**Comment by benjamin-ross** [comment]
I can tackle that one @spezzino , you want a to share the website ? Do you have a preference on where to put the button ?

**Comment by spezzino** [comment]
add them to the right of the `Total PR's` text.
The idea is to have the people share their progress _like_  
`I have completed X pull requests. Check your progress on hfchecker.stefanopy.xyz  #hacktoberfest`.

Suggestions are welcome

**Comment by UchihaCFC** [comment]
I add a twitter share button with this text. 

Do you want more social platforms? (fb ... ) I think twitter is the most important in #hacktoberfest with his hashtag.
